### ISSUE TITLE
PC way out?

### ISSUE THREAD

**Issue by danidamiobi** [xBidi/PancakeSwapPredictionBot#3]
Hi Author, brew only works for Mac. Is there a way I could install on PC? @xBidi

**Comment by xBidi** [comment]
Hi, im developing in mac, for sure you can install on PC but i dont know the commands, you will have to search in Google for that @danidamiobi

**Comment by danidamiobi** [comment]
Thanks a lot for that support Diego. Awarded the project a star and promise
to send tips to your wallet as I use the bot.

I tried using it but got a tx error. I have 24$ in my wallet in BNB and I'm
putting 5 dollar per tx. Is could that be the issue?


==

PancakeSwapPredictionBot started
Amount for bet: 0.0065 BNB
Waiting for new rounds, it can take up to 5 min
Started Epoch 19400
Waiting for 4.5 min
Getting bet amounts
Bull Amount 3.40330496625164805 BNB
Bear Amount 3.024754097535510686 BNB
Betting Bull
Tx Started
Tx Error
Started Epoch 19401
Waiting for 4.4 min
Getting bet amounts
Bull Amount 1.398272116120415205 BNB
Bear Amount 1.76951391916015899 BNB
Betting Bull
Tx Started
Tx Error
Started Epoch 19402
Waiting for 4.3 min

**Comment by danidamiobi** [comment]
I'm sorry to bug so much. What's the percent the bot gets for every success?

**Comment by danidamiobi** [comment]
Thanks for this. It now works though.
