### ISSUE TITLE
Learning models

### ISSUE THREAD

**Issue by danidamiobi** [xBidi/PancakeSwapPredictionBot#5]
Normally, any time I wish, I should just use the `npm run start` command.

However to avoid much errors do you think running the machine learning commands to build the models every 1 or 2 hours has any effect on the bot's accuracy?

**Comment by xBidi** [comment]
Actually yes, in theory you should train the model before every bet, in my testing what i have found is that a few hours between builing models change only a few percent of accuracy.

Please, test the bot with the bet code commented, if you like the performance then run the bot normally, it may have worse performance if the trend is not clear
